config/routes.rb
Rails.application.routes.draw do

  resources :schools
  # devise_for :users
  get 'students/aboutus'
  get 'students/contact'
  get 'students/latest'
  resources :students do
    member do
      get 'download_pdf'
    end
  end
  
   root to: "students#home"
   namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :students
       resources :schools
      end
    end
    
devise_for :users, controllers: {registrations: "users/registrations", omniauth_callbacks: "callbacks"}


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
    # validates :name, presence: true
      # validates :name, exclusion: { in: %w(kishore venkat), message: "%{value} is
      # reserved." }
      # validates :name, inclusion: { in: %w(kishore venkat), message: "%{value} is not in
        # the included list." }
       validates :name, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
       
      # validates :marks, numericality: true
       #validates :name, uniqueness: true
#
      #validates :name, uniqueness: { scope: :marks, message: "should happen once
      #per year" }
      # validates :name, uniqueness: { case_sensitive: false }

  # validate :name_and_subject 
  #  validates :name, presence: true, if: :check_subject_presence?
    
 # validates :marks, presence: true, unless: Proc.new{ |a| a.subject.blank?}

#   after_initialize do
#     puts "\n calling after intialize callback \n"
#   end
  ## or ##

  # after_initialize :method_after_init
  # after_find :method_after_find
  # after_find :method_after_find, if: :check_the_condition?
  # after_touch :method_after_touch 
  #  before_save :method_before_save
  # after_save :method_after_save
  #    around_save :method_around_save
  #    after_destroy :method_after_destroy
  #    after_commit :method_after_commit, on: [:create]
  #    after_rollback :method_after_rollback

  ## scopes ##
  # scope :matching, ->(q) { where(name: q)}




private

  def check_the_condition?
    true
  end
  def method_after_touch 
    puts "\n calling after touch callback \n"
  end
  def method_before_save
    puts "\n calling before save callback"
  end
  def method_after_save
    puts "\n calling after save callback \n"
  end
  def method_around_save 
    puts "\n calling before save callback \n"
    yield
    puts "\n calling after save callback \n"
  end
  def method_after_destroy 
    puts "\n calling after delete callback \n"
  end
def method_after_init
    puts "\n calling after intialize callback1 \n"

end
def method_after_find
    puts "\n calling after find callback\n"
end
def method_after_commit
    puts "\n calling after commit callback \n"
  end
  def method_after_rollback 
    puts "\n calling after rollback callback \n"
  end
  

    def check_subject_presence?
        subject == "ruby"
    end

      def name_and_subject
      if name.blank? && subject.blank?
        errors.add(:base, "name and subject cant be blank ")
      end
    end
    has_one_attached :main_image
end

app/controllers/api/v1/students_controller.rb
class Api::V1::StudentsController < ActionController::API
    def index
        students = Student.all
        render json: {message: 'OK', students: students.as_json(only: [:id, :name, :subject, :marks, :grade, :created_at])}.to_json, status: 200
        end
        def show
            student = Student.find(params[:id])
            if student
                render json: {message: 'OK', student: student}.to_json, status: 200
            else
                render json: {message: 'Error', error: 'Student not found with the given id'}.to_json, status: 404
            end
            rescue => e
                render json: {message: 'Error', error: e.message }.to_json, status: 500
            end
    def create
        student = Student.new(student_params)
        if student.save
            render json: {message: 'OK', student: student}.to_json, status: :created  
        else
            render json: {message: 'Error', error: 'stuent couldnt create'}.to_json, status: 404   
    end
end
private
        def student_params
        params.require(:student).permit(:name, :subject, :marks, :grade)
        end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    
  
    before_action :load_filters, only: ['edit','update','show','destroy','download_pdf']
    def index
       
        @students = if params[:q] && !params[:q].blank?
        
        Student.where(name: params[:q])
        
        else
        
        Student.all
        
      end
        
    end 
        def show
            
        end
        def new
            
        @student=Student.new
        end
        def create
        @student = Student.new(student_params)
        if @student.save
            StudentMailer.notify_student_creation(@student.id).deliver_now
        redirect_to students_path
        else
        render :new
        end
        end
        def edit
          
        end
        def home
            
        end

        def aboutus
            
        end
        def contact
            
        end

        def latest
        end
       

        def update
       
        if @student.update(student_params)
        redirect_to students_path
        else
        render :edit
        end
        end
            def download_pdf
                Rails.logger.debug"\n i am in dowload PDF action \n"
                send_file("#{Rails.root}/public/sample.pdf",
                filename: "#{@student.name}.pdf",
                type: "application/pdf")
                end
        
        def destroy
        @student.destroy
        redirect_to students_path
        end


        private
        def student_params
        params.require(:student).permit(:name, :subject, :marks, :grade, :main_image)
        end

        def load_filters
            
            @student = Student.find(params[:id])
        end
 end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_bootstrap.html.erb
<%= nav_bar fixed: :top do %>
  
    <%= menu_group do %>
      
       <%= menu_item "Home", root_path %>
        <%= menu_item "students list", students_path%>
        <%= menu_item "About Us", students_aboutus_path %>
        <%= menu_item "Contact", students_contact_path %>
        <div style= "padding-left:920px; padding-top:18px;">
        <%= link_to current_user.email, edit_user_registration_path(current_user) %> 
        </div>
        
      
      
     <% end %>
     <% end %>
     
  

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
    <% if @student.errors.any?  %>

<div id="error_explanation" >
<h2>
<%= pluralize(@student.errors.count, "error") %>
prohibited this student from being saved:
</h2>
<ul>
<% @student.errors.full_messages.each do |message| %>
    <li>
    <%= message %>
    <% end %>
    </ul>
    </div>

<% end %>
    <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div>
    <div>
    <%= f.label :subject %>
    <%= f.text_field :subject %>
    </div>
    <div>
    <%= f.label :marks %>
    <%= f.number_field :marks %>
    </div>
    <div>
    <%= f.label :grade %>
    <%= f.text_field :grade %>
    </div>
    <div>
    <%= f.label :main_image %>
    <%= f.file_field :main_image %>
    </div>
    <div>
    <%= f.submit %>
    </div>
    <% end %>
    <%= link_to "Back", students_path %>
    

app/views/students/_form1.html.erb
<%= form_with model: @student, method: 'get' do |f| %>

<div>

Search:

<%= f.text_field :q, value: params[:q],placeholder:'Search employee by emp_name' %>

<%= f.submit "search" %>
<%= link_to "clear", students_path %>

<% end %>

</div>

app/views/students/_form_withoutmodel.html.erb
<div>

<%= form_with url: students_path, method: 'get' do |f| %>
# form with without model
Search:

<%= f.text_field :q, value: params[:q],placeholder:'Search employee by emp_name' %>

<%= f.submit "search" %>
<%= link_to "clear", students_path %>

<% end %>

</div>

app/views/students/aboutus.html.erb
<%= render 'bootstrap' %>
<br>
<img src = "https://osidigital.com/wp-content/uploads/2018/08/osi_logo_rgb.png" style="width:400px;height:100px;">

<p><h3>At OSI Digital, we’re in the relationship business. We offer expert business and technology solutions that accelerate digital transformation for our customers. Our services include the design, development and implementation of new solutions as well as the ongoing management, enhancement and support of our customers’ existing business systems.</h3></p>
<br>
<h3>
<strong>
<center>
<%= link_to "back" ,students_path %>
</center>
</strong>
</h3>

app/views/students/contact.html.erb
<%= render 'bootstrap' %>
<br>
<h2>Hii </h2>
<h3>  Contact Us: </h3>
<center>
   <h4>Delhi Public School HYDERABAD</h4>
    <h4>survey no 74, khajaguda village,</h4>
     <h4>Chitrapuri colony road, HYDERABAD</h4>
     <h4>Telangana- 500045 </h4>
      <h4>phone no:85224-44254</h4>
      <h4>email:dps@info.com<h4>
      </center>

<%= link_to "back", :back %>
<br>

app/views/students/edit.html.erb
<br>
<%= render 'form', student: @student %>

app/views/students/home.html.erb
<%= render 'bootstrap' %>

<br>


   

app/views/students/index.html.erb
<div style="text-align:center"; ><h3><%= tag_label('Students list', :success) %></h3></div>
<div style= "text-align:right; padding-right:430px; padding-bottom:0px";><%= render 'form1', student: @student%></div>

<br>
<br>
<center>
<table border="3" bordercolor=black; >
<thead>
<br>
<th>Name</th>
<th>Subject</th>
<th>Marks</th>
<th>Grade</th>
</thead>
<tbody>
<% @students.each do |student| %>
<tr>
<td><%= student.name %> </td>
<td><%= student.subject %></td>
<td><%= student.marks %></td>
<td><%= student.grade %></td>
<td>
<%= link_to "Show", student_path(student) %>
<%= link_to "Edit", edit_student_path(student) %>
<%= link_to "delete", student_path(student), method: :delete, data: { confirm: "are u sure"} %>
<%= link_to "download PDF", download_pdf_student_path(student) %>
</td>
</tr>
<% end %>
</tbody>
</table>
<br>
<%= link_to "New",new_student_path %>
 <%= render 'bootstrap' %>
</div>
</center>

app/views/students/latest.html.erb
<%= render 'bootstrap' %>
<h1>Hi</h1>

app/views/students/new.html.erb
<br>
<%= render 'form', student: @student %>

app/views/students/show.html.erb
<%= render 'bootstrap' %>
<br>
<table>
<br>
<strong>Name:</strong>

<%= @student.name %>
</p>
<p>

<strong>Subject:</strong>

<%= @student.subject %>

</p>
<strong>Marks:</strong>

<%= @student.marks %>

</p>
<p>
<strong>Grade:</strong>

<%= @student.grade %>


<br>

<h3>Main Image:</h3>
<%= image_tag @student.main_image if @student.main_image.present? %>

</p>
<%= link_to 'Back', :back %>
</table>